import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  IconName, { BsFillBugFill, BsFillMoonStarsFill, BsGithub, BsHddNetwork, BsLinkedin, BsYoutube }  from 'react-icons/bs'
import { DiCodeBadge} from "react-icons/di"
import software from "../public/software.png"
import fiver from "../public/fiver.png"
import upwork from "../public/upwork.png"
import freelance from "../public/freelance.png"
import dh from "../public/dh.png"

import { useState ,useEffect } from "react"
import { db } from "../public/firebase-config";
import {
  collection,
  getDocs,
  addDoc,
} from "firebase/firestore";


export default function Home() {
  const [darkMode,setDarkMode] = useState(false);
  const [newMail, setnewMail] = useState("");
  const [newDescription, setNewDescription] = useState("");
  const [project, setProject] = useState([]);
  const projectCollectionRef = collection(db, "project");

  const createUser = async () => {
    await addDoc(projectCollectionRef, { mail: newMail, description: newDescription });
    
    
  };

  useEffect(() => {
    const getProject = async () => {
      const data = await getDocs(projectCollectionRef);
      console.log(data);
      
      //setProject(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    };

    getProject();
  }, []);
  return (
    <div className={darkMode ? "dark" :" "}>
      <Head>
        <title className='dark:bg-white'>BOUTCHAMIR Mounir Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px:40 dark:bg-gray-900'>
        <section className="min-h-screen" >
        <nav className='py-10 mb-12 flex justify-between dark:bg-white'>
        <h1 className='text-xl font-burtons dark:bg-white'>DevelopedbyMonirox4</h1>
        <ul className='flex items-center dark:bg-white'>
          <li>
            <BsFillMoonStarsFill 
            onClick={() => setDarkMode(!darkMode)}
            className='cursor-pointer text-2xl'/>
          </li>
          <li>
            <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
          </li>
        </ul>
        </nav>
        <div className='text-center p-10 '>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>BOUTCHAMIR Mounir</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:bg-white'>Software Engeneer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
            I'm a freelancer providing services for network equipements, doing Full-stack programming and RPA.
            It will be a pleasure to work together to make your project a reality.  
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
        <a href='https://www.linkedin.com/in/mounirboutchamir-3b8174127/'><BsLinkedin /></a>
        <a href='https://github.com/Monirox4'><BsGithub /></a>
        <a href='https://www.youtube.com/channel/UC3xfFRo84JV_1ynS3pQFQQA'><BsYoutube/></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-100 h-100 mt-100 overflow-hidden md:h-200 md:w-96'>
          <Image src={software} alt={''}  />
        </div>
        </section>
       <section>
        <div className='text-center p-10'>
          <h3 className='text-3xl py-1 dark:bg-white'>Services I offer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
          I am a junior engineer with experience in <span className='text-teal-500'>network equipment </span> and I have worked on <span className='text-teal-500'>computer systems projects</span>  .
         So I offer services in these different areas:
          </p>
          <p className='text-md py-2 leading-8 text-gray-80 dark:bg-white'>
            Application & Bugs, Network & Update & Install, Script & Languages.
          </p>
        </div>
        
          <div className='place-content-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <BsHddNetwork size={70} className='hover:place-items-center' />
          <h3 className='text-lg font-medium pt-8 pb-2'>Network & Update & Install</h3>
          <p>
          Develop network systems  in an organization to use, Improve security by creating Proxy,Vpn and Certification control .
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>Firewall</p>
          <p className='text-gray-800 py-1'>Router</p>
          <p className='text-gray-800 py-1'>AWS</p>
          </div>
        
        <div className=' shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <DiCodeBadge size={70} className='relative'/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Script & Languages</h3>
          <p>
          Programming Language to develop from scratch. Scripting Language  to combine existing components.
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>DEVops</p>
          <p className='text-gray-800 py-1'>Angular</p>
          <p className='text-gray-800 py-1'>React</p>
          </div>
          <div className='lg:center gap:10'>
          <div className=' shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <BsFillBugFill size={70}/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Application & Bugs</h3>
          <p >
          Design and Development , Make plans to quickly fix defects, Implement benchmarks and Prioritize test code.
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>Nodejs</p>
          <p className='text-gray-800 py-1'>NextJs</p>
          <p className='text-gray-800 py-1'>TestReact</p>
          </div>
        </div>
       </section>
       <section>
        
        <div className='text-center p-10'>
          <h3 className='text-3xl py-1 dark:bg-white'>Portofolio</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
          Welcome on my portofolio ! I invite you to discover my <span className='text-teal-500'> realisations</span> as well as the <span className='text-teal-500'>services</span> I offer
            
          </p>
        </div>
        <div className=' grid grid-cols-2 gap-4 place-content-center '>
        <div><a href="https://fr.fiverr.com/mounirboutchami/create-a-modern-responsive-website">
          <Image src={fiver} alt={''} width={100} height={100}  />
          </a>
        </div>
     
        <div><a href="https://www.upwork.com/freelancers/~01fab3f849b6c6e482?viewMode=1">
        <Image src={upwork} alt={''} width={100} height={100}  />
          </a>
        </div>

        <div><a href="https://www.freelancer.com/u/moonirbootchamir">
        <Image src={freelance} alt={''} width={100} height={100}  />
          </a>
        </div>
        <div><a href="https://www.designhill.com/member/moonirbootchamir/services">
        <Image src={dh} alt={''} width={100} height={100}  />
          </a>
        </div>
        </div>
       </section>
       
       


<div className="flex justify-center">
  <div className="block rounded-lg shadow-lg bg-white max-w-sm text-center">
    <div className="py-3 px-6 border-b border-gray-300">
      Contact me
    </div>
    <div className="p-6">
      <h5 className="text-gray-900 text-xl font-medium mb-2">What can I do to better serve your needs?  </h5>
           <div className="flex justify-center">
  <div className="mb-3 xl:w-96">
    <label htmlFor="exampleEmail0" className="form-label inline-block mb-2 text-gray-700"
      >Email </label
    >
    <input
      type="email"
      className="
        form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
      "
      id="exampleEmail0"
      placeholder="Email "
      onChange={(event) => {
        setnewMail(event.target.value);
      }}
    />
  </div>
</div>

<div className="flex justify-center">
  <div className="mb-3 xl:w-96">
    <label htmlFor="exampleFormControlTextarea1" className="form-label inline-block mb-2 text-gray-700"
      >Description</label
    >
    <textarea
      className="
        form-control
        block
        w-full
        px-3
        py-1.5
        text-base
        font-normal
        text-gray-700
        bg-white bg-clip-padding
        border border-solid border-gray-300
        rounded
        transition
        ease-in-out
        m-0
        focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
      "
      id="exampleFormControlTextarea1"
     
      placeholder="Your message"
      onChange={(event) => {
        setNewDescription(event.target.value);
      }}
    ></textarea>
  </div>
</div>


<div className="flex space-x-2 justify-center">
  <div>
    <button onClick={createUser} type="button" className="inline-block px-6 pt-2.5 pb-2 bg-blue-600 text-white font-medium text-xs leading-normal uppercase rounded shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-800 active:shadow-lg transition duration-150 ease-in-out align-center">
      <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="download"
        className="w-3 mr-2" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <path fill="currentColor"
          d="M216 0h80c13.3 0 24 10.7 24 24v168h87.7c17.8 0 26.7 21.5 14.1 34.1L269.7 378.3c-7.5 7.5-19.8 7.5-27.3 0L90.1 226.1c-12.6-12.6-3.7-34.1 14.1-34.1H192V24c0-13.3 10.7-24 24-24zm296 376v112c0 13.3-10.7 24-24 24H24c-13.3 0-24-10.7-24-24V376c0-13.3 10.7-24 24-24h146.7l49 49c20.1 20.1 52.5 20.1 72.6 0l49-49H488c13.3 0 24 10.7 24 24zm-124 88c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20zm64 0c0-11-9-20-20-20s-20 9-20 20 9 20 20 20 20-9 20-20z">
        </path>
      </svg>
      Send it
    </button>
  </div>
</div>
    </div>
    
    <div className="py-3 px-6 border-t border-gray-300 text-gray-600">
      Thank you 
    </div>
  </div>
</div>

      </main>


    </div>
  )
}
