import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  IconName, { BsFillBugFill, BsFillMoonStarsFill, BsGithub, BsHddNetwork, BsLinkedin, BsYoutube }  from 'react-icons/bs'
import { DiCodeBadge} from "react-icons/di"
import software from "../public/software.png"
import web1 from "../public/web1.jpg"
import web2 from "../public/web2.jpg"
import web3 from "../public/web3.jpg"
import web4 from "../public/web4.jpg"
import web5 from "../public/web5.jpg"
import web6 from "../public/web6.jpg"

import { useState } from "react"



export default function Home() {
  const [darkMode,setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" :" "}>
      <Head>
        <title className='dark:bg-white'>BOUTCHAMIR Mounir Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px:40 dark:bg-gray-900'>
        <section className="min-h-screen" >
        <nav className='py-10 mb-12 flex justify-between dark:bg-white'>
        <h1 className='text-xl font-burtons dark:bg-white'>DevelopedbyMonirox4</h1>
        <ul className='flex items-center dark:bg-white'>
          <li>
            <BsFillMoonStarsFill 
            onClick={() => setDarkMode(!darkMode)}
            className='cursor-pointer text-2xl'/>
          </li>
          <li>
            <a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a>
          </li>
        </ul>
        </nav>
        <div className='text-center p-10 '>
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>BOUTCHAMIR Mounir</h2>
          <h3 className='text-2xl py-2 md:text-3xl dark:bg-white'>Software Engeneer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
            I'm a freelancer providing services for network equipements, doing Full-stack programming and RPA.
            It will be a pleasure to work together to make your project a reality.  
          </p>
        </div>
        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
        <a href='https://www.linkedin.com/in/mounirboutchamir-3b8174127/'><BsLinkedin /></a>
        <a href='https://github.com/Monirox4'><BsGithub /></a>
        <a href='https://www.youtube.com/channel/UC3xfFRo84JV_1ynS3pQFQQA'><BsYoutube/></a>
        </div>
        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-100 h-100 mt-100 overflow-hidden md:h-200 md:w-96'>
          <Image src={software}alt={''}  />
        </div>
        </section>
       <section>
        <div className='text-center p-10'>
          <h3 className='text-3xl py-1 dark:bg-white'>Services I offer</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
          I am a junior engineer with experience in <span className='text-teal-500'>network equipment </span> and I have worked on <span className='text-teal-500'>computer systems projects</span>  .
         So I offer services in these different areas:
          </p>
          <p className='text-md py-2 leading-8 text-gray-80 dark:bg-white'>
            Application & Bugs, Network & Update & Install, Script & Languages.
          </p>
        </div>
        
          <div className='place-content-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <BsHddNetwork size={70} className='hover:place-items-center' />
          <h3 className='text-lg font-medium pt-8 pb-2'>Network & Update & Install</h3>
          <p>
          Develop network systems  in an organization to use, Improve security by creating Proxy,Vpn and Certification control .
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>Firewall</p>
          <p className='text-gray-800 py-1'>Router</p>
          <p className='text-gray-800 py-1'>AWS</p>
          </div>
        
        <div className=' shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <DiCodeBadge size={70} className='relative'/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Script & Languages</h3>
          <p>
          Programming Language to develop from scratch. Scripting Language  to combine existing components.
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>DEVops</p>
          <p className='text-gray-800 py-1'>Angular</p>
          <p className='text-gray-800 py-1'>React</p>
          </div>
          <div className='lg:center gap:10'>
          <div className=' shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
          <BsFillBugFill size={70}/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Application & Bugs</h3>
          <p >
          Design and Development , Make plans to quickly fix defects, Implement benchmarks and Prioritize test code.
          </p>
          <h4 className='py-4 text-teal-600'>Tools I use</h4>
          <p className='text-gray-800 py-1'>Nodejs</p>
          <p className='text-gray-800 py-1'>NextJs</p>
          <p className='text-gray-800 py-1'>TestReact</p>
          </div>
        </div>
       </section>
       <section>
        <div className='text-center p-10'>
          <h3 className='text-3xl py-1 dark:bg-white'>Portofolio</h3>
          <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:bg-white'>
          Welcome on my portofolio ! I invite you to discover my <span className='text-teal-500'> realisations</span> as well as the <span className='text-teal-500'>services</span> I offer
            
          </p>
        </div>
        <div className=' grid grid-cols-2 gap-4 place-content-center '>
        <div className='basis-1/2 dark:bg-white'>
        <Image src={web1}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>
        <div className='basis-1/2 flex-1 dark:bg-white'>
        <Image src={web2}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>
        <div className='basis-1/2 flex-1 dark:bg-white'>
        <Image src={web3}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>
        <div className='basis-1/2 flex-1 dark:bg-white'>
        <Image src={web4}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>
        <div className='basis-1/2 flex-1 dark:bg-white'>
        <Image src={web5}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>
        <div className='basis-1/2 flex-1 dark:bg-white'>
        <Image src={web6}  alt={''} className='rounded-lg object-cover' width={'700'} height={'700'} />
        </div>

        </div>
       </section>
      </main>


    </div>
  )
}
